"use client";
import { useMemo, useState } from "react";

type Tax = { base:string; ratePercent:string; amount:string };
export default function Home(){
  const [base,setBase]=useState("1000.00"),[ibs,setIbs]=useState("10.00"),[cbs,setCbs]=useState("5.00"); const [apiUrl,setApiUrl]=useState(process.env.NEXT_PUBLIC_API_URL??""); const [busy,setBusy]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState("");
  const calc=useMemo(()=>{const b=Number(base)||0,i=Number(ibs)||0,c=Number(cbs)||0;return {ibs:(b*i/100).toFixed(2),cbs:(b*c/100).toFixed(2),total:(b*(i+c)/100).toFixed(2)}},[base,ibs,cbs]);
  async function execute(){setBusy(true);setError("");setResult(null);try{const url=(apiUrl||"").replace(/\/$/,"");if(!url)throw new Error("Informe a URL da API");const response=await fetch(url+"/api/v1/simulations",{method:"POST",headers:{"content-type":"application/json","X-Correlation-Id":crypto.randomUUID(),"Idempotency-Key":crypto.randomUUID(),"X-Zynkronyx-Tenant":"demo"},body:JSON.stringify({executionMode:"SCENARIO",operation:{id:"WEB-"+Date.now(),issuedAt:new Date().toISOString().slice(0,10),grossAmount:Number(base).toFixed(2),currency:"BRL",items:[{id:"1",description:"Cenário web",quantity:"1",unitPrice:Number(base).toFixed(2),taxProfile:{regime:"NORMAL"}}]},rules:[{id:"IBS-WEB",tax:"IBS",validFrom:"2026-01-01",ratePercent:Number(ibs).toFixed(2),source:"WEB-SCENARIO",version:"demo"},{id:"CBS-WEB",tax:"CBS",validFrom:"2026-01-01",ratePercent:Number(cbs).toFixed(2),source:"WEB-SCENARIO",version:"demo"}]})});const data=await response.json();if(!response.ok)throw new Error(data.error||"API error");setResult(data)}catch(e){setError(e instanceof Error?e.message:"Falha na execução")}finally{setBusy(false)}}
  return <main className="shell"><header><div><span className="eyebrow">FISCAL DOMAIN</span><h1>Reforma Tributária Simulator</h1><p>Simulação fiscal, Rule Catalog e Split Payment em uma única visão.</p></div><span className="status">● ENGINE ONLINE</span></header>
  <section className="hero"><div><span className="pill">SANDBOX / SCENARIO</span><h2>Teste uma operação</h2><p>Este painel visual usa uma simulação local de cenário. As alíquotas exibidas são demonstrativas e não representam alíquotas legais.</p></div><div className="metric"><small>TOTAL TRIBUTOS</small><strong>R$ {calc.total}</strong><span>IBS + CBS</span></div></section>
  <section className="grid"><div className="card form"><h3>Operação</h3><label>Base tributável<input value={base} onChange={e=>setBase(e.target.value)}/></label><label>IBS (%)<input value={ibs} onChange={e=>setIbs(e.target.value)}/></label><label>CBS (%)<input value={cbs} onChange={e=>setCbs(e.target.value)}/></label><label>API URL<input placeholder="https://..." value={apiUrl} onChange={e=>setApiUrl(e.target.value)}/></label><button onClick={execute} disabled={busy}>{busy?"Executando...":"Executar cenário"}</button>{error&&<p className="error">{error}</p>}{result&&<pre className="result">{JSON.stringify(result,null,2)}</pre>}</div>
  <div className="card"><h3>Breakdown fiscal</h3><div className="row"><span>Base</span><b>R$ {Number(base||0).toFixed(2)}</b></div><div className="row"><span>IBS</span><b>R$ {calc.ibs}</b></div><div className="row"><span>CBS</span><b>R$ {calc.cbs}</b></div><div className="total"><span>Total</span><b>R$ {calc.total}</b></div></div>
  <div className="card"><h3>Pipeline</h3><div className="step done">01 <span>RuleSet</span><small>scenario rules</small></div><div className="step done">02 <span>Tax Engine</span><small>decimal / deterministic</small></div><div className="step">03 <span>Snapshot</span><small>D1 persistence</small></div><div className="step">04 <span>Split Payment</span><small>ledger allocation</small></div></div></section>
  <footer>Fiscal Domain Plane · Zynkronyx integration ready · v0.2</footer></main>
}